
package com.one.challenge.vistas;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Ema
 */
public class MenuPrincipal extends javax.swing.JFrame {
    public MenuPrincipal() {
        initComponents();
        initStyles();
    }
    
    private void InitContent(){
        ShowPanel(new VistaConversor());
    }
    
    private void ShowPanel(JPanel JPanel){
        JPanel.setSize(800, 500);
        JPanel.setLocation(0, 0);
        
        content.removeAll();
        content.add(JPanel, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    private void initStyles(){
        BotonComenzar.putClientProperty("JButton.buttonType", "roundRect" );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        ChallengeOne = new javax.swing.JLabel();
        BackEnd = new javax.swing.JLabel();
        ConversorDeMonedas = new javax.swing.JLabel();
        BotonComenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("menuPrincipal");

        content.setBackground(new java.awt.Color(48, 50, 61));

        ChallengeOne.setFont(new java.awt.Font("Roboto", 1, 62)); // NOI18N
        ChallengeOne.setForeground(new java.awt.Color(148, 236, 190));
        ChallengeOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChallengeOne.setText("Challenge ONE "); // NOI18N
        ChallengeOne.setToolTipText("");

        BackEnd.setFont(new java.awt.Font("Roboto", 1, 62)); // NOI18N
        BackEnd.setForeground(new java.awt.Color(71, 232, 77));
        BackEnd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackEnd.setText("Back-End"); // NOI18N
        BackEnd.setToolTipText("");

        ConversorDeMonedas.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        ConversorDeMonedas.setForeground(new java.awt.Color(138, 139, 136));
        ConversorDeMonedas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConversorDeMonedas.setText("Conversor de Monedas");

        BotonComenzar.setBackground(new java.awt.Color(148, 236, 190));
        BotonComenzar.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        BotonComenzar.setForeground(new java.awt.Color(60, 63, 65));
        BotonComenzar.setText("COMENZAR");
        BotonComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComenzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChallengeOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(BotonComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
            .addComponent(ConversorDeMonedas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(ChallengeOne)
                .addGap(0, 0, 0)
                .addComponent(BackEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(BotonComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(ConversorDeMonedas)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComenzarActionPerformed
        InitContent();  
    }//GEN-LAST:event_BotonComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal inicio = new MenuPrincipal();        
                inicio.setTitle("Conversor de Monedas");
                inicio.setVisible(true);
                inicio.setResizable(false); // Bloquear la maximización
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackEnd;
    private javax.swing.JButton BotonComenzar;
    private javax.swing.JLabel ChallengeOne;
    private javax.swing.JLabel ConversorDeMonedas;
    private javax.swing.JPanel content;
    // End of variables declaration//GEN-END:variables
}
