/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ChallengeOne.vistas;

import com.ChallengeOne.main.*;
import javax.swing.*;

/**
 *
 * @author Ema
 */
public class VistaConversor extends javax.swing.JPanel {
    private static Divisas monedaACambiar = Divisas.monedas[0];
    private static Divisas monedaDeCambio;
    
    private static String valorFinal;

    public VistaConversor() {
        initComponents();
        initStyles();
    }

    private void initStyles(){        
        // Agrega los nombres de las monedas al combo box
        String[] divisaNames = MostrarConversiones.Opciones();
        selectDivisas.setModel(new javax.swing.DefaultComboBoxModel(divisaNames));

        botonConvertir.putClientProperty( "JButton.buttonType", "roundRect" ); // Le da el Border al boton
        UIManager.put( "Component.arrowType", "triangle" ); // Cambia el estilo de la flecha 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        conversion = new javax.swing.JPanel();
        botonConvertir = new javax.swing.JButton();
        selectDivisas = new javax.swing.JComboBox<>();
        labelFrom = new javax.swing.JLabel();
        valorFrom = new javax.swing.JFormattedTextField();
        valorTo = new javax.swing.JFormattedTextField();
        labelTo = new javax.swing.JLabel();
        alternar = new javax.swing.JButton();
        heroImg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        content.setBackground(new java.awt.Color(48, 50, 61));

        conversion.setBackground(new java.awt.Color(48, 50, 61));
        conversion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        conversion.setFocusable(false);
        conversion.setPreferredSize(new java.awt.Dimension(402, 500));
        conversion.setRequestFocusEnabled(false);
        conversion.setVerifyInputWhenFocusTarget(false);

        botonConvertir.setBackground(new java.awt.Color(148, 236, 190));
        botonConvertir.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        botonConvertir.setForeground(new java.awt.Color(60, 63, 65));
        botonConvertir.setText("Convertir");
        botonConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConvertirActionPerformed(evt);
            }
        });

        selectDivisas.setBackground(new java.awt.Color(245, 245, 245));
        selectDivisas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        selectDivisas.setForeground(new java.awt.Color(30, 35, 41));
        selectDivisas.setToolTipText("");
        selectDivisas.setBorder(null);
        selectDivisas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectDivisas.setName(""); // NOI18N
        selectDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDivisasActionPerformed(evt);
            }
        });

        labelFrom.setBackground(new java.awt.Color(48, 50, 61));
        labelFrom.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelFrom.setForeground(new java.awt.Color(112, 122, 138));
        labelFrom.setText(" ");

        valorFrom.setBackground(new java.awt.Color(245, 245, 245));
        valorFrom.setForeground(new java.awt.Color(30, 35, 41));
        valorFrom.setText("0.00");
        valorFrom.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        valorFrom.setMargin(new java.awt.Insets(2, 16, 2, 16));
        valorFrom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorFromMouseClicked(evt);
            }
        });
        valorFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFromActionPerformed(evt);
            }
        });

        valorTo.setEditable(false);
        valorTo.setBackground(new java.awt.Color(245, 245, 245));
        valorTo.setForeground(new java.awt.Color(30, 35, 41));
        valorTo.setText("0.00");
        valorTo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        valorTo.setMargin(new java.awt.Insets(2, 16, 2, 16));
        valorTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorToMouseClicked(evt);
            }
        });
        valorTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorToActionPerformed(evt);
            }
        });

        labelTo.setBackground(new java.awt.Color(48, 50, 61));
        labelTo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelTo.setForeground(new java.awt.Color(112, 122, 138));
        labelTo.setText(" ");

        alternar.setBackground(new java.awt.Color(48, 50, 61));
        alternar.setForeground(new java.awt.Color(48, 50, 61));
        alternar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow_left_right.png"))); // NOI18N
        alternar.setBorder(null);
        alternar.setBorderPainted(false);
        alternar.setContentAreaFilled(false);
        alternar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alternar.setFocusPainted(false);
        alternar.setFocusable(false);
        alternar.setPreferredSize(new java.awt.Dimension(40, 40));
        alternar.setSelected(true);
        alternar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conversionLayout = new javax.swing.GroupLayout(conversion);
        conversion.setLayout(conversionLayout);
        conversionLayout.setHorizontalGroup(
            conversionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conversionLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(alternar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conversionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(conversionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTo)
                    .addComponent(labelFrom)
                    .addGroup(conversionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(selectDivisas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addComponent(botonConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );
        conversionLayout.setVerticalGroup(
            conversionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conversionLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(selectDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelFrom)
                .addGap(2, 2, 2)
                .addComponent(valorFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTo)
                .addGap(2, 2, 2)
                .addComponent(valorTo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(alternar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(botonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        heroImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Currency_Isometric.png"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(heroImg, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(conversion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conversion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(heroImg, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConvertirActionPerformed
        // TODO add your handling code here:
        //Convierte una moneda a otra y se lo setea al output
        valorFinal = Conversor.conversion(valorFrom.getText(), monedaDeCambio);
        valorTo.setText(valorFinal);
    }//GEN-LAST:event_botonConvertirActionPerformed

    private void selectDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDivisasActionPerformed
        // TODO add your handling code here:
        String divisaSeleccionada = selectDivisas.getSelectedItem().toString().strip();
        int indiceDivisa = selectDivisas.getSelectedIndex();
        
        for (Divisas e : Divisas.monedas){
            if (e.equals(Divisas.monedas[indiceDivisa])){
                monedaDeCambio = e;
                break;
            }
        }
        
        labelFrom.setText(monedaACambiar.getSigla());
        labelTo.setText(monedaDeCambio.getSigla());
    }//GEN-LAST:event_selectDivisasActionPerformed

    private void valorFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFromActionPerformed

    private void valorFromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorFromMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFromMouseClicked

    private void valorToMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorToMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_valorToMouseClicked

    private void valorToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorToActionPerformed

    private void alternarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternarActionPerformed
        // TODO add your handling code here:
        valorFinal = Conversor.conversion(valorFrom.getText(), monedaDeCambio);

        Divisas aux = monedaDeCambio;
        monedaDeCambio = monedaACambiar;
        monedaACambiar = aux;
        
        JOptionPane.showMessageDialog(null, "Proximamente", "Alerta", JOptionPane.WARNING_MESSAGE);        
        
    }//GEN-LAST:event_alternarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alternar;
    private javax.swing.JButton botonConvertir;
    private javax.swing.JPanel content;
    private javax.swing.JPanel conversion;
    private javax.swing.JLabel heroImg;
    private javax.swing.JLabel labelFrom;
    private javax.swing.JLabel labelTo;
    private javax.swing.JComboBox<String> selectDivisas;
    private javax.swing.JFormattedTextField valorFrom;
    private javax.swing.JFormattedTextField valorTo;
    // End of variables declaration//GEN-END:variables
}
